name: fire
description: Hot restart for Dart console application with fast incremental compilation.
version: 1.2.0
repository: https://github.com/ykmnkmi/fire.dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  frontend_server_client: ^3.0.0
  path: ^1.8.0
  stack_trace: ^1.10.0
  watcher: ^1.0.0

dev_dependencies:
  lints: ^2.0.0

executables:
  fire: fire